apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVMyNTJWNDMzUTRRUk1ERlg=
  AWS_SECRET_ACCESS_KEY: Yks0NENlTTcyb2pHMWdCUVZOWUpUSUMxT1g3RkNyTzhLcE5UQ0pBbQ==
